services:
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    env_file:
      - ./server/.env.development
    # environment:
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_NAME: ${POSTGRES_NAME}
    #   POSTGRES_PORT: ${POSTGRES_PORT}
    #   POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    restart: always
    image: redis:7
    env_file:
      - ./server/.env.development
    command: sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  api:
    build: ./server
    container_name: node_api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env.development
    depends_on:
      - db
      - redis
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npm run dev
      "
  web:
    build: ./client
    depends_on:
      - api
    ports:
      - "5500:5500"
    env_file:
      - ./client/.env.development
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  pgdata: {}
  redis_data: {}
