services:
  api:
    build: ./server
    container_name: node_api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env.production
    volumes:
      - ./server:/app
      - /app/node_modules
    # depends_on:
      # - db
      # - redis
